// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CanonicalNames   string
	Changelogs       string
	Domains          string
	Ipv4Addresses    string
	Ipv6Addresses    string
	MailExchangers   string
	NameServers      string
	Registrations    string
	ServerSelections string
	TextStrings      string
}{
	CanonicalNames:   "canonical_names",
	Changelogs:       "changelogs",
	Domains:          "domains",
	Ipv4Addresses:    "ipv4_addresses",
	Ipv6Addresses:    "ipv6_addresses",
	MailExchangers:   "mail_exchangers",
	NameServers:      "name_servers",
	Registrations:    "registrations",
	ServerSelections: "server_selections",
	TextStrings:      "text_strings",
}
