// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Ipv6Address is an object representing the database table.
type Ipv6Address struct {
	ID       int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	DomainID int    `boil:"domain_id" json:"domain_id" toml:"domain_id" yaml:"domain_id"`
	IP       string `boil:"ip" json:"ip" toml:"ip" yaml:"ip"`

	R *ipv6AddressR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L ipv6AddressL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var Ipv6AddressColumns = struct {
	ID       string
	DomainID string
	IP       string
}{
	ID:       "id",
	DomainID: "domain_id",
	IP:       "ip",
}

var Ipv6AddressTableColumns = struct {
	ID       string
	DomainID string
	IP       string
}{
	ID:       "ipv6_addresses.id",
	DomainID: "ipv6_addresses.domain_id",
	IP:       "ipv6_addresses.ip",
}

// Generated where

var Ipv6AddressWhere = struct {
	ID       whereHelperint
	DomainID whereHelperint
	IP       whereHelperstring
}{
	ID:       whereHelperint{field: "\"ipv6_addresses\".\"id\""},
	DomainID: whereHelperint{field: "\"ipv6_addresses\".\"domain_id\""},
	IP:       whereHelperstring{field: "\"ipv6_addresses\".\"ip\""},
}

// Ipv6AddressRels is where relationship names are stored.
var Ipv6AddressRels = struct {
	Domain string
}{
	Domain: "Domain",
}

// ipv6AddressR is where relationships are stored.
type ipv6AddressR struct {
	Domain *Domain `boil:"Domain" json:"Domain" toml:"Domain" yaml:"Domain"`
}

// NewStruct creates a new relationship struct
func (*ipv6AddressR) NewStruct() *ipv6AddressR {
	return &ipv6AddressR{}
}

func (r *ipv6AddressR) GetDomain() *Domain {
	if r == nil {
		return nil
	}
	return r.Domain
}

// ipv6AddressL is where Load methods for each relationship are stored.
type ipv6AddressL struct{}

var (
	ipv6AddressAllColumns            = []string{"id", "domain_id", "ip"}
	ipv6AddressColumnsWithoutDefault = []string{"domain_id", "ip"}
	ipv6AddressColumnsWithDefault    = []string{"id"}
	ipv6AddressPrimaryKeyColumns     = []string{"id"}
	ipv6AddressGeneratedColumns      = []string{"id"}
)

type (
	// Ipv6AddressSlice is an alias for a slice of pointers to Ipv6Address.
	// This should almost always be used instead of []Ipv6Address.
	Ipv6AddressSlice []*Ipv6Address

	ipv6AddressQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	ipv6AddressType                 = reflect.TypeOf(&Ipv6Address{})
	ipv6AddressMapping              = queries.MakeStructMapping(ipv6AddressType)
	ipv6AddressPrimaryKeyMapping, _ = queries.BindMapping(ipv6AddressType, ipv6AddressMapping, ipv6AddressPrimaryKeyColumns)
	ipv6AddressInsertCacheMut       sync.RWMutex
	ipv6AddressInsertCache          = make(map[string]insertCache)
	ipv6AddressUpdateCacheMut       sync.RWMutex
	ipv6AddressUpdateCache          = make(map[string]updateCache)
	ipv6AddressUpsertCacheMut       sync.RWMutex
	ipv6AddressUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single ipv6Address record from the query.
func (q ipv6AddressQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Ipv6Address, error) {
	o := &Ipv6Address{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for ipv6_addresses")
	}

	return o, nil
}

// All returns all Ipv6Address records from the query.
func (q ipv6AddressQuery) All(ctx context.Context, exec boil.ContextExecutor) (Ipv6AddressSlice, error) {
	var o []*Ipv6Address

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Ipv6Address slice")
	}

	return o, nil
}

// Count returns the count of all Ipv6Address records in the query.
func (q ipv6AddressQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count ipv6_addresses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q ipv6AddressQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if ipv6_addresses exists")
	}

	return count > 0, nil
}

// Domain pointed to by the foreign key.
func (o *Ipv6Address) Domain(mods ...qm.QueryMod) domainQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DomainID),
	}

	queryMods = append(queryMods, mods...)

	return Domains(queryMods...)
}

// LoadDomain allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (ipv6AddressL) LoadDomain(ctx context.Context, e boil.ContextExecutor, singular bool, maybeIpv6Address interface{}, mods queries.Applicator) error {
	var slice []*Ipv6Address
	var object *Ipv6Address

	if singular {
		var ok bool
		object, ok = maybeIpv6Address.(*Ipv6Address)
		if !ok {
			object = new(Ipv6Address)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeIpv6Address)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeIpv6Address))
			}
		}
	} else {
		s, ok := maybeIpv6Address.(*[]*Ipv6Address)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeIpv6Address)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeIpv6Address))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &ipv6AddressR{}
		}
		args = append(args, object.DomainID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &ipv6AddressR{}
			}

			for _, a := range args {
				if a == obj.DomainID {
					continue Outer
				}
			}

			args = append(args, obj.DomainID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`domains`),
		qm.WhereIn(`domains.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Domain")
	}

	var resultSlice []*Domain
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Domain")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for domains")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for domains")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Domain = foreign
		if foreign.R == nil {
			foreign.R = &domainR{}
		}
		foreign.R.Ipv6Addresses = append(foreign.R.Ipv6Addresses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DomainID == foreign.ID {
				local.R.Domain = foreign
				if foreign.R == nil {
					foreign.R = &domainR{}
				}
				foreign.R.Ipv6Addresses = append(foreign.R.Ipv6Addresses, local)
				break
			}
		}
	}

	return nil
}

// SetDomain of the ipv6Address to the related item.
// Sets o.R.Domain to related.
// Adds o to related.R.Ipv6Addresses.
func (o *Ipv6Address) SetDomain(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Domain) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ipv6_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"domain_id"}),
		strmangle.WhereClause("\"", "\"", 2, ipv6AddressPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DomainID = related.ID
	if o.R == nil {
		o.R = &ipv6AddressR{
			Domain: related,
		}
	} else {
		o.R.Domain = related
	}

	if related.R == nil {
		related.R = &domainR{
			Ipv6Addresses: Ipv6AddressSlice{o},
		}
	} else {
		related.R.Ipv6Addresses = append(related.R.Ipv6Addresses, o)
	}

	return nil
}

// Ipv6Addresses retrieves all the records using an executor.
func Ipv6Addresses(mods ...qm.QueryMod) ipv6AddressQuery {
	mods = append(mods, qm.From("\"ipv6_addresses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ipv6_addresses\".*"})
	}

	return ipv6AddressQuery{q}
}

// FindIpv6Address retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindIpv6Address(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Ipv6Address, error) {
	ipv6AddressObj := &Ipv6Address{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ipv6_addresses\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, ipv6AddressObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from ipv6_addresses")
	}

	return ipv6AddressObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Ipv6Address) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no ipv6_addresses provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(ipv6AddressColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	ipv6AddressInsertCacheMut.RLock()
	cache, cached := ipv6AddressInsertCache[key]
	ipv6AddressInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			ipv6AddressAllColumns,
			ipv6AddressColumnsWithDefault,
			ipv6AddressColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, ipv6AddressGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(ipv6AddressType, ipv6AddressMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(ipv6AddressType, ipv6AddressMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ipv6_addresses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ipv6_addresses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into ipv6_addresses")
	}

	if !cached {
		ipv6AddressInsertCacheMut.Lock()
		ipv6AddressInsertCache[key] = cache
		ipv6AddressInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Ipv6Address.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Ipv6Address) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	ipv6AddressUpdateCacheMut.RLock()
	cache, cached := ipv6AddressUpdateCache[key]
	ipv6AddressUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			ipv6AddressAllColumns,
			ipv6AddressPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, ipv6AddressGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update ipv6_addresses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ipv6_addresses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, ipv6AddressPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(ipv6AddressType, ipv6AddressMapping, append(wl, ipv6AddressPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update ipv6_addresses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for ipv6_addresses")
	}

	if !cached {
		ipv6AddressUpdateCacheMut.Lock()
		ipv6AddressUpdateCache[key] = cache
		ipv6AddressUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q ipv6AddressQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for ipv6_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for ipv6_addresses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o Ipv6AddressSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ipv6AddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ipv6_addresses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, ipv6AddressPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in ipv6Address slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all ipv6Address")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Ipv6Address) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no ipv6_addresses provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(ipv6AddressColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	ipv6AddressUpsertCacheMut.RLock()
	cache, cached := ipv6AddressUpsertCache[key]
	ipv6AddressUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			ipv6AddressAllColumns,
			ipv6AddressColumnsWithDefault,
			ipv6AddressColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			ipv6AddressAllColumns,
			ipv6AddressPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, ipv6AddressGeneratedColumns)
		update = strmangle.SetComplement(update, ipv6AddressGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert ipv6_addresses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(ipv6AddressPrimaryKeyColumns))
			copy(conflict, ipv6AddressPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ipv6_addresses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(ipv6AddressType, ipv6AddressMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(ipv6AddressType, ipv6AddressMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert ipv6_addresses")
	}

	if !cached {
		ipv6AddressUpsertCacheMut.Lock()
		ipv6AddressUpsertCache[key] = cache
		ipv6AddressUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Ipv6Address record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Ipv6Address) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Ipv6Address provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), ipv6AddressPrimaryKeyMapping)
	sql := "DELETE FROM \"ipv6_addresses\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from ipv6_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for ipv6_addresses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q ipv6AddressQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no ipv6AddressQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ipv6_addresses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ipv6_addresses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o Ipv6AddressSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ipv6AddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ipv6_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, ipv6AddressPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from ipv6Address slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for ipv6_addresses")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Ipv6Address) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindIpv6Address(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *Ipv6AddressSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := Ipv6AddressSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), ipv6AddressPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ipv6_addresses\".* FROM \"ipv6_addresses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, ipv6AddressPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in Ipv6AddressSlice")
	}

	*o = slice

	return nil
}

// Ipv6AddressExists checks if the Ipv6Address row exists.
func Ipv6AddressExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ipv6_addresses\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if ipv6_addresses exists")
	}

	return exists, nil
}

// Exists checks if the Ipv6Address row exists.
func (o *Ipv6Address) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return Ipv6AddressExists(ctx, exec, o.ID)
}
