// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ServerSelection is an object representing the database table.
type ServerSelection struct {
	ID       int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	DomainID int    `boil:"domain_id" json:"domain_id" toml:"domain_id" yaml:"domain_id"`
	Target   string `boil:"target" json:"target" toml:"target" yaml:"target"`
	Port     int    `boil:"port" json:"port" toml:"port" yaml:"port"`
	Priority int    `boil:"priority" json:"priority" toml:"priority" yaml:"priority"`
	Weight   int    `boil:"weight" json:"weight" toml:"weight" yaml:"weight"`

	R *serverSelectionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L serverSelectionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ServerSelectionColumns = struct {
	ID       string
	DomainID string
	Target   string
	Port     string
	Priority string
	Weight   string
}{
	ID:       "id",
	DomainID: "domain_id",
	Target:   "target",
	Port:     "port",
	Priority: "priority",
	Weight:   "weight",
}

var ServerSelectionTableColumns = struct {
	ID       string
	DomainID string
	Target   string
	Port     string
	Priority string
	Weight   string
}{
	ID:       "server_selections.id",
	DomainID: "server_selections.domain_id",
	Target:   "server_selections.target",
	Port:     "server_selections.port",
	Priority: "server_selections.priority",
	Weight:   "server_selections.weight",
}

// Generated where

var ServerSelectionWhere = struct {
	ID       whereHelperint
	DomainID whereHelperint
	Target   whereHelperstring
	Port     whereHelperint
	Priority whereHelperint
	Weight   whereHelperint
}{
	ID:       whereHelperint{field: "\"server_selections\".\"id\""},
	DomainID: whereHelperint{field: "\"server_selections\".\"domain_id\""},
	Target:   whereHelperstring{field: "\"server_selections\".\"target\""},
	Port:     whereHelperint{field: "\"server_selections\".\"port\""},
	Priority: whereHelperint{field: "\"server_selections\".\"priority\""},
	Weight:   whereHelperint{field: "\"server_selections\".\"weight\""},
}

// ServerSelectionRels is where relationship names are stored.
var ServerSelectionRels = struct {
	Domain string
}{
	Domain: "Domain",
}

// serverSelectionR is where relationships are stored.
type serverSelectionR struct {
	Domain *Domain `boil:"Domain" json:"Domain" toml:"Domain" yaml:"Domain"`
}

// NewStruct creates a new relationship struct
func (*serverSelectionR) NewStruct() *serverSelectionR {
	return &serverSelectionR{}
}

func (r *serverSelectionR) GetDomain() *Domain {
	if r == nil {
		return nil
	}
	return r.Domain
}

// serverSelectionL is where Load methods for each relationship are stored.
type serverSelectionL struct{}

var (
	serverSelectionAllColumns            = []string{"id", "domain_id", "target", "port", "priority", "weight"}
	serverSelectionColumnsWithoutDefault = []string{"domain_id", "target", "port", "priority", "weight"}
	serverSelectionColumnsWithDefault    = []string{"id"}
	serverSelectionPrimaryKeyColumns     = []string{"id"}
	serverSelectionGeneratedColumns      = []string{"id"}
)

type (
	// ServerSelectionSlice is an alias for a slice of pointers to ServerSelection.
	// This should almost always be used instead of []ServerSelection.
	ServerSelectionSlice []*ServerSelection
	// ServerSelectionHook is the signature for custom ServerSelection hook methods
	ServerSelectionHook func(context.Context, boil.ContextExecutor, *ServerSelection) error

	serverSelectionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	serverSelectionType                 = reflect.TypeOf(&ServerSelection{})
	serverSelectionMapping              = queries.MakeStructMapping(serverSelectionType)
	serverSelectionPrimaryKeyMapping, _ = queries.BindMapping(serverSelectionType, serverSelectionMapping, serverSelectionPrimaryKeyColumns)
	serverSelectionInsertCacheMut       sync.RWMutex
	serverSelectionInsertCache          = make(map[string]insertCache)
	serverSelectionUpdateCacheMut       sync.RWMutex
	serverSelectionUpdateCache          = make(map[string]updateCache)
	serverSelectionUpsertCacheMut       sync.RWMutex
	serverSelectionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var serverSelectionAfterSelectHooks []ServerSelectionHook

var serverSelectionBeforeInsertHooks []ServerSelectionHook
var serverSelectionAfterInsertHooks []ServerSelectionHook

var serverSelectionBeforeUpdateHooks []ServerSelectionHook
var serverSelectionAfterUpdateHooks []ServerSelectionHook

var serverSelectionBeforeDeleteHooks []ServerSelectionHook
var serverSelectionAfterDeleteHooks []ServerSelectionHook

var serverSelectionBeforeUpsertHooks []ServerSelectionHook
var serverSelectionAfterUpsertHooks []ServerSelectionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ServerSelection) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ServerSelection) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ServerSelection) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ServerSelection) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ServerSelection) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ServerSelection) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ServerSelection) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ServerSelection) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ServerSelection) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverSelectionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddServerSelectionHook registers your hook function for all future operations.
func AddServerSelectionHook(hookPoint boil.HookPoint, serverSelectionHook ServerSelectionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		serverSelectionAfterSelectHooks = append(serverSelectionAfterSelectHooks, serverSelectionHook)
	case boil.BeforeInsertHook:
		serverSelectionBeforeInsertHooks = append(serverSelectionBeforeInsertHooks, serverSelectionHook)
	case boil.AfterInsertHook:
		serverSelectionAfterInsertHooks = append(serverSelectionAfterInsertHooks, serverSelectionHook)
	case boil.BeforeUpdateHook:
		serverSelectionBeforeUpdateHooks = append(serverSelectionBeforeUpdateHooks, serverSelectionHook)
	case boil.AfterUpdateHook:
		serverSelectionAfterUpdateHooks = append(serverSelectionAfterUpdateHooks, serverSelectionHook)
	case boil.BeforeDeleteHook:
		serverSelectionBeforeDeleteHooks = append(serverSelectionBeforeDeleteHooks, serverSelectionHook)
	case boil.AfterDeleteHook:
		serverSelectionAfterDeleteHooks = append(serverSelectionAfterDeleteHooks, serverSelectionHook)
	case boil.BeforeUpsertHook:
		serverSelectionBeforeUpsertHooks = append(serverSelectionBeforeUpsertHooks, serverSelectionHook)
	case boil.AfterUpsertHook:
		serverSelectionAfterUpsertHooks = append(serverSelectionAfterUpsertHooks, serverSelectionHook)
	}
}

// One returns a single serverSelection record from the query.
func (q serverSelectionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ServerSelection, error) {
	o := &ServerSelection{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for server_selections")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ServerSelection records from the query.
func (q serverSelectionQuery) All(ctx context.Context, exec boil.ContextExecutor) (ServerSelectionSlice, error) {
	var o []*ServerSelection

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ServerSelection slice")
	}

	if len(serverSelectionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ServerSelection records in the query.
func (q serverSelectionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count server_selections rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q serverSelectionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if server_selections exists")
	}

	return count > 0, nil
}

// Domain pointed to by the foreign key.
func (o *ServerSelection) Domain(mods ...qm.QueryMod) domainQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DomainID),
	}

	queryMods = append(queryMods, mods...)

	return Domains(queryMods...)
}

// LoadDomain allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (serverSelectionL) LoadDomain(ctx context.Context, e boil.ContextExecutor, singular bool, maybeServerSelection interface{}, mods queries.Applicator) error {
	var slice []*ServerSelection
	var object *ServerSelection

	if singular {
		var ok bool
		object, ok = maybeServerSelection.(*ServerSelection)
		if !ok {
			object = new(ServerSelection)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeServerSelection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeServerSelection))
			}
		}
	} else {
		s, ok := maybeServerSelection.(*[]*ServerSelection)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeServerSelection)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeServerSelection))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &serverSelectionR{}
		}
		args = append(args, object.DomainID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &serverSelectionR{}
			}

			for _, a := range args {
				if a == obj.DomainID {
					continue Outer
				}
			}

			args = append(args, obj.DomainID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`domains`),
		qm.WhereIn(`domains.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Domain")
	}

	var resultSlice []*Domain
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Domain")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for domains")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for domains")
	}

	if len(domainAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Domain = foreign
		if foreign.R == nil {
			foreign.R = &domainR{}
		}
		foreign.R.ServerSelections = append(foreign.R.ServerSelections, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DomainID == foreign.ID {
				local.R.Domain = foreign
				if foreign.R == nil {
					foreign.R = &domainR{}
				}
				foreign.R.ServerSelections = append(foreign.R.ServerSelections, local)
				break
			}
		}
	}

	return nil
}

// SetDomain of the serverSelection to the related item.
// Sets o.R.Domain to related.
// Adds o to related.R.ServerSelections.
func (o *ServerSelection) SetDomain(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Domain) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"server_selections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"domain_id"}),
		strmangle.WhereClause("\"", "\"", 2, serverSelectionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DomainID = related.ID
	if o.R == nil {
		o.R = &serverSelectionR{
			Domain: related,
		}
	} else {
		o.R.Domain = related
	}

	if related.R == nil {
		related.R = &domainR{
			ServerSelections: ServerSelectionSlice{o},
		}
	} else {
		related.R.ServerSelections = append(related.R.ServerSelections, o)
	}

	return nil
}

// ServerSelections retrieves all the records using an executor.
func ServerSelections(mods ...qm.QueryMod) serverSelectionQuery {
	mods = append(mods, qm.From("\"server_selections\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"server_selections\".*"})
	}

	return serverSelectionQuery{q}
}

// FindServerSelection retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindServerSelection(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*ServerSelection, error) {
	serverSelectionObj := &ServerSelection{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"server_selections\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, serverSelectionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from server_selections")
	}

	if err = serverSelectionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return serverSelectionObj, err
	}

	return serverSelectionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ServerSelection) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no server_selections provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(serverSelectionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	serverSelectionInsertCacheMut.RLock()
	cache, cached := serverSelectionInsertCache[key]
	serverSelectionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			serverSelectionAllColumns,
			serverSelectionColumnsWithDefault,
			serverSelectionColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, serverSelectionGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(serverSelectionType, serverSelectionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(serverSelectionType, serverSelectionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"server_selections\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"server_selections\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into server_selections")
	}

	if !cached {
		serverSelectionInsertCacheMut.Lock()
		serverSelectionInsertCache[key] = cache
		serverSelectionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ServerSelection.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ServerSelection) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	serverSelectionUpdateCacheMut.RLock()
	cache, cached := serverSelectionUpdateCache[key]
	serverSelectionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			serverSelectionAllColumns,
			serverSelectionPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, serverSelectionGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update server_selections, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"server_selections\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, serverSelectionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(serverSelectionType, serverSelectionMapping, append(wl, serverSelectionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update server_selections row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for server_selections")
	}

	if !cached {
		serverSelectionUpdateCacheMut.Lock()
		serverSelectionUpdateCache[key] = cache
		serverSelectionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q serverSelectionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for server_selections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for server_selections")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ServerSelectionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), serverSelectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"server_selections\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, serverSelectionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in serverSelection slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all serverSelection")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ServerSelection) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no server_selections provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(serverSelectionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	serverSelectionUpsertCacheMut.RLock()
	cache, cached := serverSelectionUpsertCache[key]
	serverSelectionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			serverSelectionAllColumns,
			serverSelectionColumnsWithDefault,
			serverSelectionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			serverSelectionAllColumns,
			serverSelectionPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, serverSelectionGeneratedColumns)
		update = strmangle.SetComplement(update, serverSelectionGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert server_selections, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(serverSelectionPrimaryKeyColumns))
			copy(conflict, serverSelectionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"server_selections\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(serverSelectionType, serverSelectionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(serverSelectionType, serverSelectionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert server_selections")
	}

	if !cached {
		serverSelectionUpsertCacheMut.Lock()
		serverSelectionUpsertCache[key] = cache
		serverSelectionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ServerSelection record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ServerSelection) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ServerSelection provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), serverSelectionPrimaryKeyMapping)
	sql := "DELETE FROM \"server_selections\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from server_selections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for server_selections")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q serverSelectionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no serverSelectionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from server_selections")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for server_selections")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ServerSelectionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(serverSelectionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), serverSelectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"server_selections\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, serverSelectionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from serverSelection slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for server_selections")
	}

	if len(serverSelectionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ServerSelection) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindServerSelection(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ServerSelectionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ServerSelectionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), serverSelectionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"server_selections\".* FROM \"server_selections\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, serverSelectionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ServerSelectionSlice")
	}

	*o = slice

	return nil
}

// ServerSelectionExists checks if the ServerSelection row exists.
func ServerSelectionExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"server_selections\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if server_selections exists")
	}

	return exists, nil
}

// Exists checks if the ServerSelection row exists.
func (o *ServerSelection) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ServerSelectionExists(ctx, exec, o.ID)
}
