version: '3.8'
services:
  # cache:
  #   image: redis:6.2.11-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 60 1 --loglevel verbose --requirepass abracadabra
  #   volumes:
  #     - cache:/data
  db:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "domain"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d domain"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  postgres:
  