openapi: "3.0.0"
info:
  version: 1.0.0
  title: Inspector
servers:
  - url: http://localhost:8000
paths:
  /v1/ping:
    get:
      summary: Health check
      operationId: ping
      responses:
        200:
          description: OK
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/domain:
    get:
      summary: Get domain
      operationId: getDomain
      parameters:
        - name: fqdn
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/all-domains:
    get:
      summary: Get all stored domains FQDN
      operationId: getAllDomains
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/add-domain:
    post:
      summary: Add domain
      operationId: addDomain
      parameters:
        - name: fqdn
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/delete-domain:
    post:
      summary: Delete domain
      operationId: deleteDomain
      parameters:
        - name: fqdn
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /v1/update-domain:
    post:
      summary: Update domain
      operationId: updateDomain
      parameters:
        - name: fqdn
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    MX:
      type: object
      required:
        - host
        - pref
      properties:
        host:
          type: string
        pref:
          description: Host preference
          type: integer
          format: int64
          minimum: 0
    NS:
      type: object
      required:
        - host
      properties:
        host:
          type: string
    SRV:
      type: object
      required:
        - target
        - port
        - priority
        - weight
      properties:
        target:
          description: канонические имя машины, предоставляющей сервис
          type: string
        port:
          description: порт TCP или UDP, на котором работает сервис
          type: integer
          format: int64
          minimum: 0
        priority:
          description: приоритет целевого хоста, более низкое значение означает более предпочтительный
          type: integer
          format: int64
          minimum: 0
        weight:
          description: относительный вес для записей c одинаковым приоритетом
          type: integer
          format: int64
          minimum: 0
    TXT:
      type: string

    ResourceRecords:
      type: object
      required:
        - A
      properties:
        A:
          type: array
          items:
            type: string
            format: ipv4
        AAAA:
          type: array
          items:
            type: string
            format: ipv6
        CNAME:
          type: string
        MX:
          type: array
          items:
            $ref: "#/components/schemas/MX"
        NS:
          type: array
          items:
            $ref: "#/components/schemas/NS"
        SRV:
          type: array
          items:
            $ref: "#/components/schemas/SRV"
        TXT:
          type: array
          items:
            $ref: "#/components/schemas/TXT"
    
    WhoisRecords:
      type: object
      required:
        - domainName
        - paidTill
      properties:
        domainName:
          description: Доменное имя
          type: string
        nameServers:
          description: Список DNS-серверов, указанных для домена
          type: array
          items:
            type: string
        registrar:
          description: Регситратор домена
          type: string
        created:
          description: Дата и время регистрации домена в формате UTC
          type: string
          format: date-time
        paidTill:
          description: Дата и время окончания срока регистрации домена в формате UTC
          type: string
          format: date-time

    Domain:
      type: object
      required:
        - fqdn
        - dns
        - whois
      properties:
        fqdn:
          type: string
        dns:
          $ref: '#/components/schemas/ResourceRecords'
        whois:
          $ref: '#/components/schemas/WhoisRecords'

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string