# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: inspector

on:
  push:
    paths:
      - 'services/inspector/**'
      - '.github/workflows/inspector.yml'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'services/inspector/**'
      - '.github/workflows/inspector.yml'
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
          
      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ''
          install-mode: "goinstall"
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'services/inspector'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -C cmd/inspector .

    - name: Test
      run: go test -v ./...
