# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: inspector

on:
  push:
    paths:
      - 'services/inspector/**'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'services/inspector/**'
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'services/inspector'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -C cmd/inspector .

    - name: Test
      run: go test -v ./...
